services:
  pocketbase:
    build: ./pocketbase
    command: ["/app/pb/pocketbase", "serve", "--http=0.0.0.0:8080"]
    restart: unless-stopped
    volumes:
      - ./pocketbase/pb_migrations:/app/pb/pb_migrations
      - ./pocketbase/pb_data:/app/pb/pb_data
  web-interface:
    image: node:22-alpine
    working_dir: /app/web-interface
    env_file: .env
    command: ["sh", "-c", "npm install && npm run build"]
    volumes:
      - ./web-interface:/app/web-interface
  generate:
    build: ./generation
    command: ["fastapi", "run", "app.py"]
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./generation:/app/generation
  caddy:
    image: caddy:2-alpine
    env_file: .env
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./web-interface:/app/web-interface
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
