services:
  pocketbase:
    build: ./pocketbase
    command: ["/app/pb/pocketbase", "serve", "--http=0.0.0.0:8080"]
    restart: unless-stopped
    volumes:
      - ./pocketbase/pb_migrations:/app/pb/pb_migrations
      - ./pocketbase/pb_data:/app/pb/pb_data
  web-interface:
    image: node:22-alpine
    working_dir: /app/web-interface
    env_file: .env
    command: ["sh", "-c", "npm install && npm run build"]
    volumes:
      - ./web-interface:/app/web-interface
  redis:
    image: redis:7.4-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    restart: unless-stopped
  generation:
    build: ./generation
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "error", "--no-access-log"]
    env_file: .env

    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/generation/sqlxpert-b13d7790a7db.json
      PROJECT_ID: sqlxpert
      LOCATION: europe-west4

    restart: unless-stopped
    depends_on: 
      - redis
    volumes:
      - ./generation:/app/generation
  caddy:
    image: caddy:2-alpine
    env_file: .env
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./web-interface:/app/web-interface
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./germany_ips.caddy:/etc/caddy/germany_ips.caddy

volumes:
  caddy_data:
  caddy_config:
