name: berlin-chatbot
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - click=8.1
  - tqdm=4.67
  - pip:
      - fastapi[standard]==0.115.9
      - google-genai==1.16.1
      - httpx==0.28.1
      - openpyxl==3.1.5
      - pandas==2.2.3
      - python-dotenv==1.1.0
