name: death-bot
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - click=8.1
  - tqdm=4.67
  - pip:
      - chromadb-1.0.3
      - google-cloud-aiplatform==1.87.0
      - langchain-text-splitters==0.3.8
      - pypdf==5.4.0
      - python-dotenv==1.1.0
      - sentence-transformers[onnx]==4.0.2
